apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: app
  name: app
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
      nodePort: 30001
  selector:
    io.kompose.service: app
