- name: Ensure Python and pip are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Install Python dependencies
  pip:
    requirements: "{{ working_dir }}/requirements.txt"
    executable: pip3

- name: Run application in background
  ansible.builtin.shell: nohup ./run.sh &
  args:
    chdir: "{{ working_dir }}"
